sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - ./build_all.sh

script:
  - docker run tyabu12/ocaml  ocaml -version
  - docker run tyabu12/debian
  - docker run tyabu12/coq    coqtop -v
  - docker run tyabu12/coqide coqtop -v
  - docker run tyabu12/eliom  ocsigenserver.opt --version

after_success:
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/tyabu/ocaml/trigger/${OCAML_TRIGGER_TOKEN}/
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/tyabu/debian/trigger/${DEBIAN_TRIGGER_TOKEN}/
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/tyabu/coq/trigger/${COQ_TRIGGER_TOKEN}/
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/tyabu/coqide/trigger/${COQIDE_TRIGGER_TOKEN}/
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/tyabu/eliom/trigger/${ELIOM_TRIGGER_TOKEN}/

