sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - ./build_all.sh

script:
  - docker run tyabu12/debian
  - docker run tyabu12/coq    coqtop -v
  - docker run tyabu12/coqide coqtop -v
  - docker run tyabu12/eliom  ocsigenserver.opt --version
  - docker run tyabu12/ocaml  ocaml -version
