sudo: required
language: bash
services: docker

env:
  - NAME=debian VERSION=
  - NAME=ocaml VERSION=4.07
  - NAME=ocaml VERSION=4.06
  - NAME=opam VERSION=2.0
  - NAME=coq VERSION=8.8
  - NAME=coq VERSION=8.7
  - NAME=coqide VERSION=8.7
  - NAME=coqide VERSION=8.6
  - NAME=eliom VERSION=6.3

cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker images

before_script:
  - dockerfile_path="$NAME/$VERSION"
  - image_name="tyabu/${NAME}:${VERSION:-latest}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image_name" "$dockerfile_path"
    )

before_cache:
  - docker image prune -f
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

after_success:
  - docker images

jobs:
  include:
    - stage: trigger docker hub
      cache: {}
      before_install: skip
      before_script: skip
      script: skip
      before_cache: skip
      after_success:
        - ./trigger.sh debian $DEBIAN_TRIGGER_TOKEN
        - ./trigger.sh ocaml $OCAML_TRIGGER_TOKEN

