sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - ./build_all.sh

script:
  - docker run tyabu/ocaml  ocaml --version
  - docker run tyabu/opam   opam  --version
  - docker run tyabu/debian
  - docker run tyabu/coq    coqtop -v
  - docker run tyabu/coqide coqtop -v
  - docker run tyabu/eliom  ocsigenserver.opt --version

after_success:
  - ./trigger_all.sh

