sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker build -t tyabu/base base
  - docker build -t tyabu/coq coq
  - docker build -t tyabu/coqide coqide
  - docker build -t tyabu/eliom:6.2.0 eliom/6.2.0

script:
  - docker run tyabu/base
  - docker run tyabu/coq coqtop -v
  - docker run tyabu/eliom:6.2.0 ocsigenserver.opt --version
