sudo: required

language: bash

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_script:
  - ./build_all.sh

script:
  - docker run tyabu/ocaml  ocaml --version
  - docker run tyabu/opam   opam  --version
  - docker run tyabu/debian
  - docker run tyabu/coq    coqtop -v
  - docker run tyabu/coqide coqtop -v
  - docker run tyabu/eliom  ocsigenserver.opt --version

after_success:
  - ./trigger_all.sh

